package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name = "Actividad")
public class Actividad implements java.io.Serializable {

	@Id
	@Column(name = "actividad")
	private String actividad;

	public Actividad() {
	}

	public Actividad(String actividad) {
		this.actividad = actividad;
	}

	public String getActividad() {
		return this.actividad;
	}

	public void setActividad(String actividad) {
		this.actividad = actividad;
	}

}
