package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private AdminId id;

	public Admin() {
	}

	public Admin(AdminId id) {
		this.id = id;
	}

	public AdminId getId() {
		return this.id;
	}

	public void setId(AdminId id) {
		this.id = id;
	}

}
