package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

/**
 * Continentes generated by hbm2java
 */
public class Continentes implements java.io.Serializable {

	private String continente;

	public Continentes() {
	}

	public Continentes(String continente) {
		this.continente = continente;
	}

	public String getContinente() {
		return this.continente;
	}

	public void setContinente(String continente) {
		this.continente = continente;
	}

}
