package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Destinaciones generated by hbm2java
 */

@Entity
@Table(name = "Destinaciones")
public class Destinaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id")
	private Integer id;

	@Column(name = "ciudad")
	private String ciudad;

	@Column(name = "cp")
	private String cp;

	@Column(name = "playa")
	private String playa;

	@Column(name = "web")
	private String web;

	@Column(name = "itinerario")
	private String itinerario;

	@Column(name = "capital")
	private String capital;

	@Column(name = "pais")
	private String pais;

	@Column(name = "continente")
	private String continente;

	@Column(name = "imagen")
	private String imagen;

	public Destinaciones() {
	}

	public Destinaciones(String ciudad, String cp, String playa, String web, String itinerario, String capital,
			String pais, String continente, String imagen) {
		this.ciudad = ciudad;
		this.cp = cp;
		this.playa = playa;
		this.web = web;
		this.itinerario = itinerario;
		this.capital = capital;
		this.pais = pais;
		this.continente = continente;
		this.imagen = imagen;

	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public String getPlaya() {
		return this.playa;
	}

	public void setPlaya(String playa) {
		this.playa = playa;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getItinerario() {
		return this.itinerario;
	}

	public void setItinerario(String itinerario) {
		this.itinerario = itinerario;
	}

	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getContinente() {
		return this.continente;
	}

	public void setContinente(String continente) {
		this.continente = continente;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

}
