package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

/**
 * LogsId generated by hbm2java
 */
public class LogsId implements java.io.Serializable {

	private Integer iduser;
	private String nom;
	private String action;
	private String where;

	public LogsId() {
	}

	public LogsId(Integer iduser, String nom, String action, String where) {
		this.iduser = iduser;
		this.nom = nom;
		this.action = action;
		this.where = where;
	}

	public Integer getIduser() {
		return this.iduser;
	}

	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getWhere() {
		return this.where;
	}

	public void setWhere(String where) {
		this.where = where;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogsId))
			return false;
		LogsId castOther = (LogsId) other;

		return ((this.getIduser() == castOther.getIduser()) || (this.getIduser() != null
				&& castOther.getIduser() != null && this.getIduser().equals(castOther.getIduser())))
				&& ((this.getNom() == castOther.getNom()) || (this.getNom() != null && castOther.getNom() != null
						&& this.getNom().equals(castOther.getNom())))
				&& ((this.getAction() == castOther.getAction()) || (this.getAction() != null
						&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& ((this.getWhere() == castOther.getWhere()) || (this.getWhere() != null
						&& castOther.getWhere() != null && this.getWhere().equals(castOther.getWhere())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIduser() == null ? 0 : this.getIduser().hashCode());
		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (getWhere() == null ? 0 : this.getWhere().hashCode());
		return result;
	}

}
