package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

/**
 * Logs generated by hbm2java
 */
public class Logs implements java.io.Serializable {

	private LogsId id;

	public Logs() {
	}

	public Logs(LogsId id) {
		this.id = id;
	}

	public LogsId getId() {
		return this.id;
	}

	public void setId(LogsId id) {
		this.id = id;
	}

}
