package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Puntosinteres generated by hbm2java
 */

@Entity
@Table(name = "Puntosinteres")
public class Puntosinteres implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id")
	private Integer id;

	@Column(name = "iddestinacion")
	private Integer iddestinacion;

	@Column(name = "nombre")
	private String nombre;

	@Column(name = "descripcion")
	private String descripcion;

	@Column(name = "tipo")
	private String tipo;

	@Column(name = "actividades")
	private String actividades;

	public Puntosinteres() {
	}

	public Puntosinteres(Integer id, String nombre, String descripcion, String tipo, String actividades) {

		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.actividades = actividades;
	}

	public Integer getIddestinacion() {
		return this.iddestinacion;
	}

	public void setIddestinacion(Integer iddestinacion) {
		this.iddestinacion = iddestinacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getActividades() {
		return this.actividades;
	}

	public void setActividades(String actividades) {
		this.actividades = actividades;
	}

}
