package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private UsuariosId id;

	public Usuarios() {
	}

	public Usuarios(UsuariosId id) {
		this.id = id;
	}

	public UsuariosId getId() {
		return this.id;
	}

	public void setId(UsuariosId id) {
		this.id = id;
	}

}
