package copiaTablas;
// Generated 14-jul-2017 10:03:07 by Hibernate Tools 4.3.5.Final

/**
 * UsuariosId generated by hbm2java
 */
public class UsuariosId implements java.io.Serializable {

	private Integer id;
	private Integer nif;
	private Integer nombre;
	private Integer apellido;
	private Integer poblacion;
	private Integer cp;
	private Integer telefono;
	private Integer email;
	private Integer fnacimiento;

	public UsuariosId() {
	}

	public UsuariosId(Integer id, Integer nif, Integer nombre, Integer apellido, Integer poblacion, Integer cp,
			Integer telefono, Integer email, Integer fnacimiento) {
		this.id = id;
		this.nif = nif;
		this.nombre = nombre;
		this.apellido = apellido;
		this.poblacion = poblacion;
		this.cp = cp;
		this.telefono = telefono;
		this.email = email;
		this.fnacimiento = fnacimiento;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNif() {
		return this.nif;
	}

	public void setNif(Integer nif) {
		this.nif = nif;
	}

	public Integer getNombre() {
		return this.nombre;
	}

	public void setNombre(Integer nombre) {
		this.nombre = nombre;
	}

	public Integer getApellido() {
		return this.apellido;
	}

	public void setApellido(Integer apellido) {
		this.apellido = apellido;
	}

	public Integer getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(Integer poblacion) {
		this.poblacion = poblacion;
	}

	public Integer getCp() {
		return this.cp;
	}

	public void setCp(Integer cp) {
		this.cp = cp;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public Integer getEmail() {
		return this.email;
	}

	public void setEmail(Integer email) {
		this.email = email;
	}

	public Integer getFnacimiento() {
		return this.fnacimiento;
	}

	public void setFnacimiento(Integer fnacimiento) {
		this.fnacimiento = fnacimiento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariosId))
			return false;
		UsuariosId castOther = (UsuariosId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getNif() == castOther.getNif()) || (this.getNif() != null && castOther.getNif() != null
						&& this.getNif().equals(castOther.getNif())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellido() == castOther.getApellido()) || (this.getApellido() != null
						&& castOther.getApellido() != null && this.getApellido().equals(castOther.getApellido())))
				&& ((this.getPoblacion() == castOther.getPoblacion()) || (this.getPoblacion() != null
						&& castOther.getPoblacion() != null && this.getPoblacion().equals(castOther.getPoblacion())))
				&& ((this.getCp() == castOther.getCp()) || (this.getCp() != null && castOther.getCp() != null
						&& this.getCp().equals(castOther.getCp())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getFnacimiento() == castOther.getFnacimiento())
						|| (this.getFnacimiento() != null && castOther.getFnacimiento() != null
								&& this.getFnacimiento().equals(castOther.getFnacimiento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getNif() == null ? 0 : this.getNif().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellido() == null ? 0 : this.getApellido().hashCode());
		result = 37 * result + (getPoblacion() == null ? 0 : this.getPoblacion().hashCode());
		result = 37 * result + (getCp() == null ? 0 : this.getCp().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getFnacimiento() == null ? 0 : this.getFnacimiento().hashCode());
		return result;
	}

}
